Add 05 to the student list
ava8katushka/tech_skills_for_pm2 pull request #6
Opened 2021-02-22 12:06 UTC by GamificationLab

Add Vasilina Zhonkina to the student list

2021-02-22 13:12 UTC, ava8katushka requested changes
Please address the comments and resolve the conflicts.

2021-02-22 13:12 UTC, ava8katushka commented on Add 05 to the student list
> +| 5 | Василина Жонкина     | Автостопом по галактике                             |
Please fix the layout of the table. All "|" should be in the same line (you must move it in all the table). 
And also incorporate commits from other people into your submission (you are not the number 5 in this table).

2021-02-23 22:14 UTC, ava8katushka commented
Please, resolve the conflicts.

2021-02-24 12:21 UTC, ava8katushka commented
Vasilina, I would like to accept your pull request, but you need to learn how to resolve the conflicts.
Try going to https://github.com/ava8katushka/tech_skills_for_pm2/  and clicking on your pull request. 
You would see the grey panel with the button "Resolve conflicts".

2021-02-24 12:36 UTC, GamificationLab commented
У меня эта кнопка неактивна, я не могу на нее нажать (

2021-02-24 12:45 UTC, ava8katushka commented
Да, теперь вижу. Говорит что конфликты слишком сложные чтобы решить в UI.

2021-02-24 12:46 UTC, ava8katushka commented
Но можно сначала сделать pull новых изменений в свой репозиторий.

2021-02-24 13:03 UTC, ava8katushka commented
Окей, кажется даже в этом случае не получится обойтись без командной строки :(  Слишком сложные конфликты

2021-02-24 13:21 UTC, ava8katushka commented
Ну вот кажется есть два варианта:
1. Попробовать разрешить конфликты с помощью командной строки или GitHub Desktop.
2. Создать новый pull request в репозиторий.

2021-02-24 17:33 UTC, ava8katushka commented on Add 05 to the student list
> +# Технические навыки для PM
please delete this file

2021-02-24 17:35 UTC, ava8katushka commented
Really cool you find out how to get from unsolvable conflicts stage.
If  you just resolve the conflicts with the button now and delete the extra file, and should be ready to go.

2021-02-25 14:51 UTC, ava8katushka commented on README.md
> +| 13 | Василина Жонкина| Автостопом по галактике               |
Could you please arrange all the "|" to be in the same line? You can do it by shifting right all the "|" above  Василина Жонкина

2021-02-25 14:51 UTC, ava8katushka commented
And resolve new conflicts.

2021-02-25 15:01 UTC, ava8katushka commented
I know you've done a lot during this exercise.

2021-02-25 16:25 UTC, merged