Add Goryunova to the student list
ava8katushka/tech_skills_for_pm2 pull request #8
Opened 2021-02-22 17:20 UTC by GoryunovaA

2021-02-23 15:38 UTC, ava8katushka commented
Please resolve the conflicts.

2021-02-23 16:46 UTC, GoryunovaA commented
Ready

2021-02-23 17:21 UTC, ava8katushka commented
There are conflicts unresolved.

2021-02-23 17:22 UTC, ava8katushka requested changes

2021-02-23 17:22 UTC, ava8katushka commented on README.md
> +| 4 | Настя Горюнова  | Унесённые ветром                       |
Number 4 couldn't go after number 2.

2021-02-23 23:19 UTC, GoryunovaA commented
One more time

2021-02-24 05:48 UTC, ava8katushka commented
You try to make your file look ready by adding all the people from the list (and it does look ready), but it's not accepted by git because conflicts are unresolved. 
![2021-02-24_08-46-14](https://user-images.githubusercontent.com/73282400/108953863-f302c780-767c-11eb-8a9e-b596c9cbf36e.png)

2021-02-24 06:39 UTC, GoryunovaA commented
Unfortunately, I have no idea what I should do in order to resolve the conflict

2021-02-24 07:31 UTC, ava8katushka commented
That's okay. Let's figure out together.
1. Go to https://github.com/ava8katushka/tech_skills_for_pm2/ and see your pull request in the list.
2. Click on it. 
3. You would see the window to resolve the conflicts.

2021-02-24 08:04 UTC, GoryunovaA commented
Seems like it's OK now

2021-02-24 10:03 UTC, merged